# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='local',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
