# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-05 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.DateField()),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ano Lectivo',
                'verbose_name_plural': 'Anos LEctivos',
                'ordering': ['criado'],
            },
        ),
    ]
