# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anolectivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anolectivo',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='anolectivo',
            name='criado',
            field=models.DateTimeField(default=datetime.date(2018, 12, 16)),
        ),
    ]
