# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anolectivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anolectivo',
            options={'verbose_name': 'Ano Lectivo', 'verbose_name_plural': 'Ano lectivo'},
        ),
    ]
