# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anolectivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anolectivo',
            name='ano',
            field=models.IntegerField(max_length=15),
        ),
    ]
