# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anolectivo', '0002_auto_20190208_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anolectivo',
            name='ano',
            field=models.PositiveIntegerField(max_length=15),
        ),
    ]
