# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anolectivo', '0002_auto_20181216_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anolectivo',
            name='criado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
