# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anolectivo', '0002_auto_20181203_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anolectivo',
            options={'ordering': ('ano',), 'verbose_name': 'Ano Lectivo', 'verbose_name_plural': 'Ano lectivo'},
        ),
    ]
