# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anolectivo', '0003_auto_20190209_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anolectivo',
            name='ano',
            field=models.PositiveIntegerField(default='2019', max_length=15),
        ),
    ]
