# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anolectivo', '0003_auto_20181216_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anolectivo',
            options={'ordering': ['criado'], 'verbose_name': 'Ano Lectivo', 'verbose_name_plural': 'Anos LEctivos'},
        ),
    ]
