# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anolectivo', '0004_auto_20190209_0707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anolectivo',
            options={'ordering': ['criado'], 'verbose_name': 'Ano Lectivo', 'verbose_name_plural': 'Anos Lectivos'},
        ),
    ]
