# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meses', '0003_auto_20181216_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meses',
            options={'ordering': ['criado'], 'verbose_name': 'Mes', 'verbose_name_plural': 'Meses'},
        ),
    ]
