# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmas',
            name='disciplina',
            field=models.ManyToManyField(blank=True, to='disciplinas.Disciplina'),
        ),
    ]
