# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turmas',
            old_name='estudante',
            new_name='responsavel',
        ),
    ]
