# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anolectivo', '0001_initial'),
        ('salas', '0002_turmas_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmas',
            name='estudante',
        ),
        migrations.AddField(
            model_name='turmas',
            name='anolectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anolectivo.AnoLectivo'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='responsavel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
