# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_auto_20190115_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmas',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='turmas',
            name='numero_sala',
            field=models.IntegerField(default=0),
        ),
    ]
