# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0004_auto_20190126_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmas',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da sala'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='numero_sala',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Número da sala'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='periodo',
            field=models.CharField(blank=True, choices=[('N', 'Noite'), ('M', 'Manha'), ('T', 'Tarde'), ('E', 'Selecionar periodo')], default='E', max_length=1, null=True, verbose_name='Periodo da turma'),
        ),
    ]
