# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0004_auto_20181212_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turmas',
            old_name='turma',
            new_name='nome',
        ),
    ]
