# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salas', '0005_auto_20190126_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmas',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='turmas',
            name='professores',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
