# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 02:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salas', '0007_turmas_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmas',
            name='estudandates',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='responsavel',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
