# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 02:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0008_auto_20181220_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmas',
            name='estudandates',
        ),
        migrations.AlterField(
            model_name='turmas',
            name='responsavel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
