# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 02:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salas', '0009_auto_20181220_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmas',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='turmas',
            name='estudante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
