# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 08:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salas', '0010_auto_20181220_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmas',
            name='estudante',
        ),
        migrations.AddField(
            model_name='turmas',
            name='estudante',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
