# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='noBI',
            field=models.CharField(max_length=100, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='sobrenome',
            field=models.CharField(max_length=255, verbose_name='Sobrenome '),
        ),
    ]
