# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_auto_20181219_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='enviado',
            field=models.DateTimeField(default=datetime.date(2018, 12, 19)),
        ),
        migrations.AddField(
            model_name='candidato',
            name='novo',
            field=models.BooleanField(default=True),
        ),
    ]
