# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_servico',
            field=models.CharField(blank=True, choices=[('P', 'Propina'), ('M', 'Matricula')], default='M', max_length=1, null=True, verbose_name='Tipo de serviço'),
        ),
    ]
