# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_auto_20190208_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='prestacao',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
