# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=255)),
                ('turma', models.ManyToManyField(blank=True, null=True, to='salas.Turmas')),
            ],
        ),
    ]
