# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 11:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=250, verbose_name='Primeiro nome')),
                ('segundo_nome', models.CharField(max_length=250, verbose_name='Segundo nome')),
                ('tipo_perfil', models.CharField(choices=[('A', 'Administrador'), ('F', 'Funcionario'), ('E', 'Estudante'), ('P', 'Professor')], default='E', max_length=1, verbose_name='Tipo de peerfil')),
                ('morada', models.CharField(max_length=250, verbose_name='nome da turma')),
                ('foto', models.FileField(default='perfil/default.jpg', upload_to='perfil/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
