# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='turma',
            field=models.ManyToManyField(null=True, to='salas.Turmas'),
        ),
    ]
