# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='disciplina',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.CharField(blank=True, choices=[('A', 'Administrador'), ('F', 'Funcionario'), ('E', 'Estudante'), ('P', 'Professor')], default='F', max_length=1, null=True, verbose_name='Tipo de perfil'),
        ),
    ]
