# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.FileField(blank=True, default='perfil/default.jpg', null=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='morada',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='nome da turma'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='segundo_nome',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Segundo nome'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.CharField(blank=True, choices=[('A', 'Administrador'), ('F', 'Funcionario'), ('E', 'Estudante'), ('P', 'Professor')], default='E', max_length=1, null=True, verbose_name='Tipo de peerfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
