# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_auto_20181211_0800'),
        ('usuarios', '0002_perfil_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salas.Turmas'),
        ),
    ]
