# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20181122_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='morada',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='nome da turma'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='primeiro_nome',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='segundo_nome',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Segundo nome'),
        ),
    ]
