# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0005_auto_20181212_1046'),
        ('usuarios', '0002_auto_20181212_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='turma',
        ),
        migrations.AddField(
            model_name='perfil',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salas.Turmas'),
        ),
    ]
