# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_auto_20181122_1316'),
        ('usuarios', '0003_auto_20181122_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='departamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departamentos.Departamentos'),
        ),
    ]
