# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propinas', '0002_auto_20181216_2033'),
        ('usuarios', '0003_auto_20181212_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='propinas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propinas.Propinas'),
        ),
    ]
