# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departamentos.Departamentos'),
        ),
    ]
