# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20181216_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.CharField(blank=True, choices=[('A', 'Administrador'), ('F', 'Funcionario'), ('E', 'Estudante'), ('P', 'Professor')], default='F', max_length=1, null=True, verbose_name='Tipo de peerfil'),
        ),
    ]
