# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anolectivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ano_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anolectivo.AnoLectivo')),
            ],
        ),
    ]
