# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anolectivo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propina', models.IntegerField(default=0)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anolectivo.AnoLectivo')),
                ('estundante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meses.Meses')),
            ],
        ),
    ]
