# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propinas',
            options={'verbose_name': 'Pronina', 'verbose_name_plural': 'Propinas'},
        ),
    ]
