# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propinas', '0002_auto_20181216_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propinas',
            options={'get_latest_by': 'mes', 'verbose_name': 'Pronina', 'verbose_name_plural': 'Propinas'},
        ),
    ]
