# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propinas', '0004_propinas_prestacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propinas',
            old_name='total_propinas',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='propinas',
            name='propina',
        ),
    ]
