# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0008_auto_20190114_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('sobre_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('propinas', models.IntegerField(default=0)),
                ('disciplinas', models.ManyToManyField(blank=True, to='disciplinas.Disciplina')),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
            },
        ),
    ]
