# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_disciplina'),
        ('estudantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudantes',
            name='user',
        ),
        migrations.AddField(
            model_name='estudantes',
            name='peril',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil'),
        ),
    ]
