# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('estudantes', '0001_initial'),
        ('salas', '0005_auto_20190126_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudantes',
            name='peril',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil'),
        ),
        migrations.AddField(
            model_name='estudantes',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salas.Turmas'),
        ),
    ]
