# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudantes', '0002_auto_20190131_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudantes',
            name='telefone',
        ),
        migrations.AddField(
            model_name='estudantes',
            name='nome_encarregado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estudantes',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
