# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudantes', '0002_auto_20190114_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudantes',
            name='propinas',
            field=models.IntegerField(default=0),
        ),
    ]
