# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0008_auto_20190114_2023'),
        ('estudantes', '0003_estudantes_propinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudantes',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, to='disciplinas.Disciplina'),
        ),
    ]
