# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0002_auto_20181203_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=255)),
                ('periodo', models.CharField(blank=True, choices=[('N', 'Noite'), ('M', 'Manha'), ('T', 'Tarde'), ('E', 'Selecionar periodo')], default='E', max_length=1, null=True, verbose_name='Tipo de peerfil')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Cursos')),
                ('estudante', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'turmas',
            },
        ),
    ]
