# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0002_mensagem_lido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='lido',
            new_name='por_ler',
        ),
    ]
