# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0003_auto_20181219_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='enviado',
            field=models.DateTimeField(default=datetime.date(2018, 12, 19)),
        ),
    ]
