# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamentos', '0002_auto_20181122_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentos',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='departamentos',
            name='funcionario',
            field=models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
