# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_auto_20181122_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentos',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
    ]
