# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0002_auto_20181205_1532'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nota', models.FloatField()),
                ('estudante', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('turma', models.ManyToManyField(blank=True, to='turmas.Turmas')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
            },
        ),
    ]
