# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-05 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplinas', '0002_remove_disciplina_estudante'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='estudante',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
