# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('disciplinas', '0005_remove_disciplina_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.Cursos'),
        ),
    ]
