# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('disciplinas', '0006_disciplina_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='curso',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ManyToManyField(blank=True, to='cursos.Cursos'),
        ),
    ]
