# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0007_auto_20190114_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='estudante',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
